add support for custom domains on containers
scaleway/serverless-scaleway-functions pull request #105
Opened 2022-09-05 11:59 UTC by thomas-tacquet

2022-09-06 14:18 UTC, RamyChaabane commented on deploy/lib/createContainers.js
> +          existingDomains.forEach((existingDom) => {
I think there is a better way to do this, for loop in a for loop is not a good practice

2022-09-08 11:04 UTC, norbjd requested changes

2022-09-08 11:04 UTC, norbjd commented on README.md
> +[custom domains on Container](https://www.scaleway.com/en/docs/compute/containers/how-to/add-a-custom-domain-to-a-container/)
```suggestion
For domain configuration please refer to [custom domains documentation on Function](https://www.scaleway.com/en/docs/compute/functions/how-to/add-a-custom-domain-name-to-a-function/) or
[custom domains documentation on Container](https://www.scaleway.com/en/docs/compute/containers/how-to/add-a-custom-domain-to-a-container/)
```

2022-09-08 11:04 UTC, norbjd commented on deploy/lib/createContainers.js
> +  applyDomainsContainer(containerId, customDomains) {
A test would be great :+1:

2022-09-08 16:00 UTC, norbjd commented on deploy/lib/createFunctions.js
> +    this.listDomainsFunction(funcId).then((domains) => {
Is the block after `(domains) => {` the same as in the `applyDomainsContainer`. If so, can you extract the code to a function and reuse it?

2022-09-08 16:21 UTC, norbjd approved these changes

2022-09-09 13:31 UTC, merged